//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:55:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class bebidaDTO
    {
        [DataMember()]
        public Int32 bebida_id { get; set; }

        [DataMember()]
        public Double precio { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public List<minibarDTO> minibar { get; set; }

        public bebidaDTO()
        {
        }

        public bebidaDTO(Int32 bebida_id, Double precio, String nombre, List<minibarDTO> minibar)
        {
			this.bebida_id = bebida_id;
			this.precio = precio;
			this.nombre = nombre;
			this.minibar = minibar;
        }
    }
}
