//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:55:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class categoria_habitacionDTO
    {
        [DataMember()]
        public Int32 categoria_id { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public Double porcentaje { get; set; }

        [DataMember()]
        public List<habitacionDTO> habitacion { get; set; }

        public categoria_habitacionDTO()
        {
        }

        public categoria_habitacionDTO(Int32 categoria_id, String nombre, Double porcentaje, List<habitacionDTO> habitacion)
        {
			this.categoria_id = categoria_id;
			this.nombre = nombre;
			this.porcentaje = porcentaje;
			this.habitacion = habitacion;
        }
    }
}
