//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:55:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class comprobanteDTO
    {
        [DataMember()]
        public Int32 id { get; set; }

        [DataMember()]
        public Int32 cliente_id { get; set; }

        [DataMember()]
        public Int32 reserva_id { get; set; }

        [DataMember()]
        public Nullable<Double> costeHabitacion { get; set; }

        [DataMember()]
        public Nullable<Double> costeLlamadas { get; set; }

        [DataMember()]
        public Nullable<Double> costeMinibar { get; set; }

        [DataMember()]
        public Nullable<Double> costeConsumibles { get; set; }

        [DataMember()]
        public String RUCcliente { get; set; }

        [DataMember()]
        public Int32 idcomprobante { get; set; }

        [DataMember()]
        public Nullable<DateTime> FechaeEmision { get; set; }

        [DataMember()]
        public Nullable<Int16> estado { get; set; }

        [DataMember()]
        public EmpresaDTO Empresa { get; set; }

        [DataMember()]
        public TipoComprobanteDTO TipoComprobante { get; set; }

        [DataMember()]
        public reservaDTO reserva { get; set; }

        [DataMember()]
        public userDTO user { get; set; }

        public comprobanteDTO()
        {
        }

        public comprobanteDTO(Int32 id, Int32 cliente_id, Int32 reserva_id, Nullable<Double> costeHabitacion, Nullable<Double> costeLlamadas, Nullable<Double> costeMinibar, Nullable<Double> costeConsumibles, String rUCcliente, Int32 idcomprobante, Nullable<DateTime> fechaeEmision, Nullable<Int16> estado, EmpresaDTO empresa, TipoComprobanteDTO tipoComprobante, reservaDTO reserva, userDTO user)
        {
			this.id = id;
			this.cliente_id = cliente_id;
			this.reserva_id = reserva_id;
			this.costeHabitacion = costeHabitacion;
			this.costeLlamadas = costeLlamadas;
			this.costeMinibar = costeMinibar;
			this.costeConsumibles = costeConsumibles;
			this.RUCcliente = rUCcliente;
			this.idcomprobante = idcomprobante;
			this.FechaeEmision = fechaeEmision;
			this.estado = estado;
			this.Empresa = empresa;
			this.TipoComprobante = tipoComprobante;
			this.reserva = reserva;
			this.user = user;
        }
    }
}
