//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:55:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class EmpresaDTO
    {
        [DataMember()]
        public String RUC { get; set; }

        [DataMember()]
        public String RazonSocial { get; set; }

        [DataMember()]
        public String Direccion { get; set; }

        [DataMember()]
        public String Telefono { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public List<comprobanteDTO> comprobante { get; set; }

        public EmpresaDTO()
        {
        }

        public EmpresaDTO(String rUC, String razonSocial, String direccion, String telefono, String email, List<comprobanteDTO> comprobante)
        {
			this.RUC = rUC;
			this.RazonSocial = razonSocial;
			this.Direccion = direccion;
			this.Telefono = telefono;
			this.Email = email;
			this.comprobante = comprobante;
        }
    }
}
