//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:55:59
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class hotelDTO
    {
        [DataMember()]
        public Int32 hotel_id { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public Int32 estrellas { get; set; }

        [DataMember()]
        public String direccion { get; set; }

        [DataMember()]
        public String ciudad { get; set; }

        [DataMember()]
        public String telefono { get; set; }

        [DataMember()]
        public List<habitacionDTO> habitacion { get; set; }

        public hotelDTO()
        {
        }

        public hotelDTO(Int32 hotel_id, String nombre, Int32 estrellas, String direccion, String ciudad, String telefono, List<habitacionDTO> habitacion)
        {
			this.hotel_id = hotel_id;
			this.nombre = nombre;
			this.estrellas = estrellas;
			this.direccion = direccion;
			this.ciudad = ciudad;
			this.telefono = telefono;
			this.habitacion = habitacion;
        }
    }
}
