//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class minibarDTO
    {
        [DataMember()]
        public Int32 id { get; set; }

        [DataMember()]
        public Int32 reserva_id { get; set; }

        [DataMember()]
        public Int32 habitacion_id { get; set; }

        [DataMember()]
        public Int32 bebida_id { get; set; }

        [DataMember()]
        public Int32 cantidad_consumida { get; set; }

        [DataMember()]
        public bebidaDTO bebida { get; set; }

        [DataMember()]
        public habitacionDTO habitacion { get; set; }

        public minibarDTO()
        {
        }

        public minibarDTO(Int32 id, Int32 reserva_id, Int32 habitacion_id, Int32 bebida_id, Int32 cantidad_consumida, bebidaDTO bebida, habitacionDTO habitacion)
        {
			this.id = id;
			this.reserva_id = reserva_id;
			this.habitacion_id = habitacion_id;
			this.bebida_id = bebida_id;
			this.cantidad_consumida = cantidad_consumida;
			this.bebida = bebida;
			this.habitacion = habitacion;
        }
    }
}
