//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class reservaDTO
    {
        [DataMember()]
        public Int32 reserva_id { get; set; }

        [DataMember()]
        public Int32 cliente_id { get; set; }

        [DataMember()]
        public DateTime fecha_inicio { get; set; }

        [DataMember()]
        public DateTime fecha_fin { get; set; }

        [DataMember()]
        public DateTime fecha_reserva { get; set; }

        [DataMember()]
        public List<comprobanteDTO> comprobante { get; set; }

        [DataMember()]
        public userDTO user { get; set; }

        [DataMember()]
        public List<reserva_habitacionDTO> reserva_habitacion { get; set; }

        public reservaDTO()
        {
        }

        public reservaDTO(Int32 reserva_id, Int32 cliente_id, DateTime fecha_inicio, DateTime fecha_fin, DateTime fecha_reserva, List<comprobanteDTO> comprobante, userDTO user, List<reserva_habitacionDTO> reserva_habitacion)
        {
			this.reserva_id = reserva_id;
			this.cliente_id = cliente_id;
			this.fecha_inicio = fecha_inicio;
			this.fecha_fin = fecha_fin;
			this.fecha_reserva = fecha_reserva;
			this.comprobante = comprobante;
			this.user = user;
			this.reserva_habitacion = reserva_habitacion;
        }
    }
}
