//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class reserva_habitacionDTO
    {
        [DataMember()]
        public Int32 id { get; set; }

        [DataMember()]
        public Int32 reserva_id { get; set; }

        [DataMember()]
        public Int32 habitacion_id { get; set; }

        [DataMember()]
        public habitacionDTO habitacion { get; set; }

        [DataMember()]
        public reservaDTO reserva { get; set; }

        public reserva_habitacionDTO()
        {
        }

        public reserva_habitacionDTO(Int32 id, Int32 reserva_id, Int32 habitacion_id, habitacionDTO habitacion, reservaDTO reserva)
        {
			this.id = id;
			this.reserva_id = reserva_id;
			this.habitacion_id = habitacion_id;
			this.habitacion = habitacion;
			this.reserva = reserva;
        }
    }
}
