//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Dominio.Dtos
{
    [DataContract()]
    public partial class userDTO
    {
        [DataMember()]
        public Int32 user_id { get; set; }

        [DataMember()]
        public String username { get; set; }

        [DataMember()]
        public String password { get; set; }

        [DataMember()]
        public String email { get; set; }

        [DataMember()]
        public String dni { get; set; }

        [DataMember()]
        public String nombre { get; set; }

        [DataMember()]
        public String apellidos { get; set; }

        [DataMember()]
        public String direccion { get; set; }

        [DataMember()]
        public String telefono { get; set; }

        [DataMember()]
        public Nullable<Int16> enabled { get; set; }

        [DataMember()]
        public Nullable<Int16> accountExpired { get; set; }

        [DataMember()]
        public Nullable<Int16> accountLocked { get; set; }

        [DataMember()]
        public Nullable<Int16> passwordExpired { get; set; }

        [DataMember()]
        public String RUC { get; set; }

        [DataMember()]
        public List<comprobanteDTO> comprobante { get; set; }

        [DataMember()]
        public List<reservaDTO> reserva { get; set; }

        [DataMember()]
        public List<user_roleDTO> user_role { get; set; }

        public userDTO()
        {
        }

        public userDTO(Int32 user_id, String username, String password, String email, String dni, String nombre, String apellidos, String direccion, String telefono, Nullable<Int16> enabled, Nullable<Int16> accountExpired, Nullable<Int16> accountLocked, Nullable<Int16> passwordExpired, String rUC, List<comprobanteDTO> comprobante, List<reservaDTO> reserva, List<user_roleDTO> user_role)
        {
			this.user_id = user_id;
			this.username = username;
			this.password = password;
			this.email = email;
			this.dni = dni;
			this.nombre = nombre;
			this.apellidos = apellidos;
			this.direccion = direccion;
			this.telefono = telefono;
			this.enabled = enabled;
			this.accountExpired = accountExpired;
			this.accountLocked = accountLocked;
			this.passwordExpired = passwordExpired;
			this.RUC = rUC;
			this.comprobante = comprobante;
			this.reserva = reserva;
			this.user_role = user_role;
        }
    }
}
