//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:04
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="categoria_habitacion"/> and <see cref="categoria_habitacionDTO"/>.
    /// </summary>
    public static partial class categoria_habitacionAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="categoria_habitacionDTO"/> converted from <see cref="categoria_habitacion"/>.</param>
        static partial void OnDTO(this categoria_habitacion entity, categoria_habitacionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="categoria_habitacion"/> converted from <see cref="categoria_habitacionDTO"/>.</param>
        static partial void OnEntity(this categoria_habitacionDTO dto, categoria_habitacion entity);

        /// <summary>
        /// Converts this instance of <see cref="categoria_habitacionDTO"/> to an instance of <see cref="categoria_habitacion"/>.
        /// </summary>
        /// <param name="dto"><see cref="categoria_habitacionDTO"/> to convert.</param>
        public static categoria_habitacion ToEntity(this categoria_habitacionDTO dto)
        {
            if (dto == null) return null;

            var entity = new categoria_habitacion();

            entity.categoria_id = dto.categoria_id;
            entity.nombre = dto.nombre;
            entity.porcentaje = dto.porcentaje;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="categoria_habitacion"/> to an instance of <see cref="categoria_habitacionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="categoria_habitacion"/> to convert.</param>
        public static categoria_habitacionDTO ToDTO(this categoria_habitacion entity)
        {
            if (entity == null) return null;

            var dto = new categoria_habitacionDTO();

            dto.categoria_id = entity.categoria_id;
            dto.nombre = entity.nombre;
            dto.porcentaje = entity.porcentaje;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="categoria_habitacionDTO"/> to an instance of <see cref="categoria_habitacion"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<categoria_habitacion> ToEntities(this IEnumerable<categoria_habitacionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="categoria_habitacion"/> to an instance of <see cref="categoria_habitacionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<categoria_habitacionDTO> ToDTOs(this IEnumerable<categoria_habitacion> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.categoria_habitacionDTO dto, PersistenciaDatos.categoria_habitacion entity)
        {
            entity.categoria_id = dto.categoria_id;
            entity.nombre = dto.nombre;
            entity.porcentaje = dto.porcentaje;

        }
    }
}
