//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="habitacion"/> and <see cref="habitacionDTO"/>.
    /// </summary>
    public static partial class habitacionAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="habitacionDTO"/> converted from <see cref="habitacion"/>.</param>
        static partial void OnDTO(this habitacion entity, habitacionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="habitacion"/> converted from <see cref="habitacionDTO"/>.</param>
        static partial void OnEntity(this habitacionDTO dto, habitacion entity);

        /// <summary>
        /// Converts this instance of <see cref="habitacionDTO"/> to an instance of <see cref="habitacion"/>.
        /// </summary>
        /// <param name="dto"><see cref="habitacionDTO"/> to convert.</param>
        public static habitacion ToEntity(this habitacionDTO dto)
        {
            if (dto == null) return null;

            var entity = new habitacion();

            entity.habitacion_id = dto.habitacion_id;
            entity.hotel_id = dto.hotel_id;
            entity.categoria_id = dto.categoria_id;
            entity.tipo_habitacion_id = dto.tipo_habitacion_id;
            entity.ocupada = dto.ocupada;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="habitacion"/> to an instance of <see cref="habitacionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="habitacion"/> to convert.</param>
        public static habitacionDTO ToDTO(this habitacion entity)
        {
            if (entity == null) return null;

            var dto = new habitacionDTO();

            dto.habitacion_id = entity.habitacion_id;
            dto.hotel_id = entity.hotel_id;
            dto.categoria_id = entity.categoria_id;
            dto.tipo_habitacion_id = entity.tipo_habitacion_id;
            dto.ocupada = entity.ocupada;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="habitacionDTO"/> to an instance of <see cref="habitacion"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<habitacion> ToEntities(this IEnumerable<habitacionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="habitacion"/> to an instance of <see cref="habitacionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<habitacionDTO> ToDTOs(this IEnumerable<habitacion> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.habitacionDTO dto, PersistenciaDatos.habitacion entity)
        {
            entity.habitacion_id = dto.habitacion_id;
            entity.hotel_id = dto.hotel_id;
            entity.categoria_id = dto.categoria_id;
            entity.tipo_habitacion_id = dto.tipo_habitacion_id;
            entity.ocupada = dto.ocupada;

        }
    }
}
