//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="hotel"/> and <see cref="hotelDTO"/>.
    /// </summary>
    public static partial class hotelAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="hotelDTO"/> converted from <see cref="hotel"/>.</param>
        static partial void OnDTO(this hotel entity, hotelDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="hotel"/> converted from <see cref="hotelDTO"/>.</param>
        static partial void OnEntity(this hotelDTO dto, hotel entity);

        /// <summary>
        /// Converts this instance of <see cref="hotelDTO"/> to an instance of <see cref="hotel"/>.
        /// </summary>
        /// <param name="dto"><see cref="hotelDTO"/> to convert.</param>
        public static hotel ToEntity(this hotelDTO dto)
        {
            if (dto == null) return null;

            var entity = new hotel();

            entity.hotel_id = dto.hotel_id;
            entity.nombre = dto.nombre;
            entity.estrellas = dto.estrellas;
            entity.direccion = dto.direccion;
            entity.ciudad = dto.ciudad;
            entity.telefono = dto.telefono;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="hotel"/> to an instance of <see cref="hotelDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="hotel"/> to convert.</param>
        public static hotelDTO ToDTO(this hotel entity)
        {
            if (entity == null) return null;

            var dto = new hotelDTO();

            dto.hotel_id = entity.hotel_id;
            dto.nombre = entity.nombre;
            dto.estrellas = entity.estrellas;
            dto.direccion = entity.direccion;
            dto.ciudad = entity.ciudad;
            dto.telefono = entity.telefono;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="hotelDTO"/> to an instance of <see cref="hotel"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<hotel> ToEntities(this IEnumerable<hotelDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="hotel"/> to an instance of <see cref="hotelDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<hotelDTO> ToDTOs(this IEnumerable<hotel> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.hotelDTO dto, PersistenciaDatos.hotel entity)
        {
            entity.hotel_id = dto.hotel_id;
            entity.nombre = dto.nombre;
            entity.estrellas = dto.estrellas;
            entity.direccion = dto.direccion;
            entity.ciudad = dto.ciudad;
            entity.telefono = dto.telefono;

        }
    }
}
