//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="llamada"/> and <see cref="llamadaDTO"/>.
    /// </summary>
    public static partial class llamadaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="llamadaDTO"/> converted from <see cref="llamada"/>.</param>
        static partial void OnDTO(this llamada entity, llamadaDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="llamada"/> converted from <see cref="llamadaDTO"/>.</param>
        static partial void OnEntity(this llamadaDTO dto, llamada entity);

        /// <summary>
        /// Converts this instance of <see cref="llamadaDTO"/> to an instance of <see cref="llamada"/>.
        /// </summary>
        /// <param name="dto"><see cref="llamadaDTO"/> to convert.</param>
        public static llamada ToEntity(this llamadaDTO dto)
        {
            if (dto == null) return null;

            var entity = new llamada();

            entity.llamada_id = dto.llamada_id;
            entity.reserva_id = dto.reserva_id;
            entity.habitacion_id = dto.habitacion_id;
            entity.tipo_llamada_id = dto.tipo_llamada_id;
            entity.minutos = dto.minutos;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="llamada"/> to an instance of <see cref="llamadaDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="llamada"/> to convert.</param>
        public static llamadaDTO ToDTO(this llamada entity)
        {
            if (entity == null) return null;

            var dto = new llamadaDTO();

            dto.llamada_id = entity.llamada_id;
            dto.reserva_id = entity.reserva_id;
            dto.habitacion_id = entity.habitacion_id;
            dto.tipo_llamada_id = entity.tipo_llamada_id;
            dto.minutos = entity.minutos;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="llamadaDTO"/> to an instance of <see cref="llamada"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<llamada> ToEntities(this IEnumerable<llamadaDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="llamada"/> to an instance of <see cref="llamadaDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<llamadaDTO> ToDTOs(this IEnumerable<llamada> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.llamadaDTO dto, PersistenciaDatos.llamada entity)
        {
            entity.llamada_id = dto.llamada_id;
            entity.reserva_id = dto.reserva_id;
            entity.habitacion_id = dto.habitacion_id;
            entity.tipo_llamada_id = dto.tipo_llamada_id;
            entity.minutos = dto.minutos;

        }
    }
}
