//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="minibar"/> and <see cref="minibarDTO"/>.
    /// </summary>
    public static partial class minibarAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="minibarDTO"/> converted from <see cref="minibar"/>.</param>
        static partial void OnDTO(this minibar entity, minibarDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="minibar"/> converted from <see cref="minibarDTO"/>.</param>
        static partial void OnEntity(this minibarDTO dto, minibar entity);

        /// <summary>
        /// Converts this instance of <see cref="minibarDTO"/> to an instance of <see cref="minibar"/>.
        /// </summary>
        /// <param name="dto"><see cref="minibarDTO"/> to convert.</param>
        public static minibar ToEntity(this minibarDTO dto)
        {
            if (dto == null) return null;

            var entity = new minibar();

            entity.id = dto.id;
            entity.reserva_id = dto.reserva_id;
            entity.habitacion_id = dto.habitacion_id;
            entity.bebida_id = dto.bebida_id;
            entity.cantidad_consumida = dto.cantidad_consumida;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="minibar"/> to an instance of <see cref="minibarDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="minibar"/> to convert.</param>
        public static minibarDTO ToDTO(this minibar entity)
        {
            if (entity == null) return null;

            var dto = new minibarDTO();

            dto.id = entity.id;
            dto.reserva_id = entity.reserva_id;
            dto.habitacion_id = entity.habitacion_id;
            dto.bebida_id = entity.bebida_id;
            dto.cantidad_consumida = entity.cantidad_consumida;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="minibarDTO"/> to an instance of <see cref="minibar"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<minibar> ToEntities(this IEnumerable<minibarDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="minibar"/> to an instance of <see cref="minibarDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<minibarDTO> ToDTOs(this IEnumerable<minibar> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.minibarDTO dto, PersistenciaDatos.minibar entity)
        {
            entity.id = dto.id;
            entity.reserva_id = dto.reserva_id;
            entity.habitacion_id = dto.habitacion_id;
            entity.bebida_id = dto.bebida_id;
            entity.cantidad_consumida = dto.cantidad_consumida;

        }
    }
}
