//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="role"/> and <see cref="roleDTO"/>.
    /// </summary>
    public static partial class roleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="roleDTO"/> converted from <see cref="role"/>.</param>
        static partial void OnDTO(this role entity, roleDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="role"/> converted from <see cref="roleDTO"/>.</param>
        static partial void OnEntity(this roleDTO dto, role entity);

        /// <summary>
        /// Converts this instance of <see cref="roleDTO"/> to an instance of <see cref="role"/>.
        /// </summary>
        /// <param name="dto"><see cref="roleDTO"/> to convert.</param>
        public static role ToEntity(this roleDTO dto)
        {
            if (dto == null) return null;

            var entity = new role();

            entity.role_id = dto.role_id;
            entity.authority = dto.authority;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="role"/> to an instance of <see cref="roleDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="role"/> to convert.</param>
        public static roleDTO ToDTO(this role entity)
        {
            if (entity == null) return null;

            var dto = new roleDTO();

            dto.role_id = entity.role_id;
            dto.authority = entity.authority;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="roleDTO"/> to an instance of <see cref="role"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<role> ToEntities(this IEnumerable<roleDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="role"/> to an instance of <see cref="roleDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<roleDTO> ToDTOs(this IEnumerable<role> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.roleDTO dto, PersistenciaDatos.role entity)
        {
            entity.role_id = dto.role_id;
            entity.authority = dto.authority;

        }
    }
}
