//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="tipo_habitacion"/> and <see cref="tipo_habitacionDTO"/>.
    /// </summary>
    public static partial class tipo_habitacionAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tipo_habitacionDTO"/> converted from <see cref="tipo_habitacion"/>.</param>
        static partial void OnDTO(this tipo_habitacion entity, tipo_habitacionDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tipo_habitacion"/> converted from <see cref="tipo_habitacionDTO"/>.</param>
        static partial void OnEntity(this tipo_habitacionDTO dto, tipo_habitacion entity);

        /// <summary>
        /// Converts this instance of <see cref="tipo_habitacionDTO"/> to an instance of <see cref="tipo_habitacion"/>.
        /// </summary>
        /// <param name="dto"><see cref="tipo_habitacionDTO"/> to convert.</param>
        public static tipo_habitacion ToEntity(this tipo_habitacionDTO dto)
        {
            if (dto == null) return null;

            var entity = new tipo_habitacion();

            entity.tipo_habitacion_id = dto.tipo_habitacion_id;
            entity.nombre = dto.nombre;
            entity.precio = dto.precio;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tipo_habitacion"/> to an instance of <see cref="tipo_habitacionDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tipo_habitacion"/> to convert.</param>
        public static tipo_habitacionDTO ToDTO(this tipo_habitacion entity)
        {
            if (entity == null) return null;

            var dto = new tipo_habitacionDTO();

            dto.tipo_habitacion_id = entity.tipo_habitacion_id;
            dto.nombre = entity.nombre;
            dto.precio = entity.precio;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tipo_habitacionDTO"/> to an instance of <see cref="tipo_habitacion"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tipo_habitacion> ToEntities(this IEnumerable<tipo_habitacionDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tipo_habitacion"/> to an instance of <see cref="tipo_habitacionDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tipo_habitacionDTO> ToDTOs(this IEnumerable<tipo_habitacion> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.tipo_habitacionDTO dto, PersistenciaDatos.tipo_habitacion entity)
        {
            entity.tipo_habitacion_id = dto.tipo_habitacion_id;
            entity.nombre = dto.nombre;
            entity.precio = dto.precio;

        }
    }
}
