//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:06
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="tipo_llamada"/> and <see cref="tipo_llamadaDTO"/>.
    /// </summary>
    public static partial class tipo_llamadaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tipo_llamadaDTO"/> converted from <see cref="tipo_llamada"/>.</param>
        static partial void OnDTO(this tipo_llamada entity, tipo_llamadaDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tipo_llamada"/> converted from <see cref="tipo_llamadaDTO"/>.</param>
        static partial void OnEntity(this tipo_llamadaDTO dto, tipo_llamada entity);

        /// <summary>
        /// Converts this instance of <see cref="tipo_llamadaDTO"/> to an instance of <see cref="tipo_llamada"/>.
        /// </summary>
        /// <param name="dto"><see cref="tipo_llamadaDTO"/> to convert.</param>
        public static tipo_llamada ToEntity(this tipo_llamadaDTO dto)
        {
            if (dto == null) return null;

            var entity = new tipo_llamada();

            entity.tipo_llamada_id = dto.tipo_llamada_id;
            entity.nombre = dto.nombre;
            entity.precio = dto.precio;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tipo_llamada"/> to an instance of <see cref="tipo_llamadaDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tipo_llamada"/> to convert.</param>
        public static tipo_llamadaDTO ToDTO(this tipo_llamada entity)
        {
            if (entity == null) return null;

            var dto = new tipo_llamadaDTO();

            dto.tipo_llamada_id = entity.tipo_llamada_id;
            dto.nombre = entity.nombre;
            dto.precio = entity.precio;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tipo_llamadaDTO"/> to an instance of <see cref="tipo_llamada"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tipo_llamada> ToEntities(this IEnumerable<tipo_llamadaDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tipo_llamada"/> to an instance of <see cref="tipo_llamadaDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tipo_llamadaDTO> ToDTOs(this IEnumerable<tipo_llamada> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }
        public static void Actualizar(Dominio.Dtos.tipo_llamadaDTO dto, PersistenciaDatos.tipo_llamada entity)
        {


            entity.tipo_llamada_id = dto.tipo_llamada_id;
            entity.nombre = dto.nombre;
            entity.precio = dto.precio;


        }
    }
}
