//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/06/15 - 08:56:07
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Dominio.Dtos;
using PersistenciaDatos;

namespace Dominio.Convertidores
{

    /// <summary>
    /// Assembler for <see cref="user_role"/> and <see cref="user_roleDTO"/>.
    /// </summary>
    public static partial class user_roleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="user_roleDTO"/> converted from <see cref="user_role"/>.</param>
        static partial void OnDTO(this user_role entity, user_roleDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="user_role"/> converted from <see cref="user_roleDTO"/>.</param>
        static partial void OnEntity(this user_roleDTO dto, user_role entity);

        /// <summary>
        /// Converts this instance of <see cref="user_roleDTO"/> to an instance of <see cref="user_role"/>.
        /// </summary>
        /// <param name="dto"><see cref="user_roleDTO"/> to convert.</param>
        public static user_role ToEntity(this user_roleDTO dto)
        {
            if (dto == null) return null;

            var entity = new user_role();

            entity.id = dto.id;
            entity.user_id = dto.user_id;
            entity.role_id = dto.role_id;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="user_role"/> to an instance of <see cref="user_roleDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="user_role"/> to convert.</param>
        public static user_roleDTO ToDTO(this user_role entity)
        {
            if (entity == null) return null;

            var dto = new user_roleDTO();

            dto.id = entity.id;
            dto.user_id = entity.user_id;
            dto.role_id = entity.role_id;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="user_roleDTO"/> to an instance of <see cref="user_role"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<user_role> ToEntities(this IEnumerable<user_roleDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="user_role"/> to an instance of <see cref="user_roleDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<user_roleDTO> ToDTOs(this IEnumerable<user_role> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

        public static void Actualizar(Dominio.Dtos.user_roleDTO  dto, PersistenciaDatos.user_role  entity)
        {

            entity.id = dto.id;
            entity.user_id = dto.user_id;
            entity.role_id = dto.role_id;
           
        }

    }
}
