//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bebida
    {
        public bebida()
        {
            this.minibar = new HashSet<minibar>();
        }
    
        public int bebida_id { get; set; }
        public double precio { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<minibar> minibar { get; set; }
    }
}
