//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int reserva_id { get; set; }
        public Nullable<double> costeHabitacion { get; set; }
        public Nullable<double> costeLlamadas { get; set; }
        public Nullable<double> costeMinibar { get; set; }
        public Nullable<double> costeConsumibles { get; set; }
        public string RUCcliente { get; set; }
        public int idcomprobante { get; set; }
        public Nullable<System.DateTime> FechaeEmision { get; set; }
        public Nullable<short> estado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual TipoComprobante TipoComprobante { get; set; }
        public virtual reserva reserva { get; set; }
        public virtual user user { get; set; }
    }
}
