//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        public habitacion()
        {
            this.minibar = new HashSet<minibar>();
            this.llamada = new HashSet<llamada>();
            this.reserva_habitacion = new HashSet<reserva_habitacion>();
        }
    
        public int habitacion_id { get; set; }
        public int hotel_id { get; set; }
        public int categoria_id { get; set; }
        public int tipo_habitacion_id { get; set; }
        public short ocupada { get; set; }
    
        public virtual categoria_habitacion categoria_habitacion { get; set; }
        public virtual ICollection<minibar> minibar { get; set; }
        public virtual hotel hotel { get; set; }
        public virtual tipo_habitacion tipo_habitacion { get; set; }
        public virtual ICollection<llamada> llamada { get; set; }
        public virtual ICollection<reserva_habitacion> reserva_habitacion { get; set; }
    }
}
