//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        public hotel()
        {
            this.habitacion = new HashSet<habitacion>();
        }
    
        public int hotel_id { get; set; }
        public string nombre { get; set; }
        public int estrellas { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<habitacion> habitacion { get; set; }
    }
}
