//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class llamada
    {
        public int llamada_id { get; set; }
        public int reserva_id { get; set; }
        public int habitacion_id { get; set; }
        public int tipo_llamada_id { get; set; }
        public Nullable<double> minutos { get; set; }
    
        public virtual habitacion habitacion { get; set; }
        public virtual tipo_llamada tipo_llamada { get; set; }
    }
}
