//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HostalDBEntities : DbContext
    {
        public HostalDBEntities()
            : base("name=HostalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bebida> bebida { get; set; }
        public DbSet<categoria_habitacion> categoria_habitacion { get; set; }
        public DbSet<comprobante> comprobante { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<habitacion> habitacion { get; set; }
        public DbSet<hotel> hotel { get; set; }
        public DbSet<llamada> llamada { get; set; }
        public DbSet<minibar> minibar { get; set; }
        public DbSet<reserva> reserva { get; set; }
        public DbSet<reserva_habitacion> reserva_habitacion { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public DbSet<tipo_llamada> tipo_llamada { get; set; }
        public DbSet<TipoComprobante> TipoComprobante { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_role> user_role { get; set; }
    }
}
