//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public reserva()
        {
            this.comprobante = new HashSet<comprobante>();
            this.reserva_habitacion = new HashSet<reserva_habitacion>();
        }
    
        public int reserva_id { get; set; }
        public int cliente_id { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public System.DateTime fecha_reserva { get; set; }
    
        public virtual ICollection<comprobante> comprobante { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<reserva_habitacion> reserva_habitacion { get; set; }
    }
}
