//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int role_id { get; set; }
    
        public virtual role role { get; set; }
        public virtual user user { get; set; }
    }
}
