//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.comprobante = new HashSet<comprobante>();
            this.reserva = new HashSet<reserva>();
            this.user_role = new HashSet<user_role>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string dni { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public Nullable<short> enabled { get; set; }
        public Nullable<short> accountExpired { get; set; }
        public Nullable<short> accountLocked { get; set; }
        public Nullable<short> passwordExpired { get; set; }
        public string RUC { get; set; }
    
        public virtual ICollection<comprobante> comprobante { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
        public virtual ICollection<user_role> user_role { get; set; }
    }
}
